spring:
  application:
    name: rest-with-spring-boot-and-java

  datasource:
    url: jdbc:mariadb://localhost:3306/ESTUDO_JAVA
    username: root
    password: meteoro85
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # Pode ser 'validate', 'create', 'create-drop', etc.
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info
    org.hibernate.type.descriptor.sql.BasicExtractor: info
    br.com.thiagohmm: info
